FROM java:6
MAINTAINER GAMACORE info@gamacore.ma
RUN cd /tmp
RUN wget http://www-eu.apache.org/dist/tomcat/tomcat-7/v7.0.96/bin/apache-tomcat-7.0.96.tar.gz
RUN tar xvf apache-tomcat-7.0.96.tar.gz -C /tmp
RUN rm -rf  apache-tomcat-7.0.96.tar.gz
RUN mv /tmp/apache-tomcat-7.0.96 /tmp/tomcat
RUN mv /tmp/tomcat /opt
WORKDIR /opt/tomcat

EXPOSE 8080

CMD ["./bin/catalina.sh", "run"]

# construire avec : docker build -t tomcat6mederp .
# lancer avec : docker run -p 5555:8080 -v /tmp/webapps:/opt/tomcat/webapps -d --name tomcat.advanceeur tomcat6mederp
