FROM java:8
MAINTAINER Ossama Boughaba boughaba@gmail.com
RUN cd /tmp
RUN wget http://www.mederp.net/downloads/tomcat-8.tar.gz
RUN tar xvf tomcat-8.tar.gz -C /tmp
RUN rm -rf  tomcat-8.tar.gz
RUN mv /tmp/tomcat /opt
WORKDIR /opt/tomcat

EXPOSE 8080

CMD ["./bin/catalina.sh", "run"]

# construire avec : docker build -t tomcat8mederp .
# pour l'appli gestion, lancer avec : 
# docker run -p 8001:8080 -v /usr/local/gestion/webapps:/opt/tomcat/webapps -v /usr/local/gestion/db:/usr/local/gestion -v /usr/local/gestion/logs:/opt/tomcat/logs  -d --name tomcat.gestion rezzix/mederp:tomcat8
