FROM java:8
MAINTAINER Ossama Boughaba boughaba@gmail.com
RUN cd /tmp
RUN wget http://www.mederp.net/downloads/tomcat-8.tar.gz
RUN tar xvf tomcat-8.tar.gz -C /tmp
RUN rm -rf  tomcat-8.tar.gz
RUN mv /tmp/tomcat /opt
WORKDIR /opt/tomcat

EXPOSE 8080

CMD ["./bin/catalina.sh", "run"]

# construire avec : docker build -t tomcat8mederp .
# lancer avec : docker run -p 5555:8080 -v /tmp/webapps:/opt/tomcat/webapps -d --name tomcat.erasme tomcat8mederp